export const newArrivals = [
  {
    id: 1,
    name: "V-neck cotton T-shirt",
    price: 59.99,
    image: ["/ecom/women-2.jpg"],
    size: ["S", "M", "L", "XL"],
    colors: ["red", "blue", "green"],
    discountPercent: "",
    oldPrice: "",
  },
  {
    id: 2,
    name: "Polarized sunglasses",
    price: 79.54,
    image: ["/ecom/women-9.jpg"],
    size: [],
    colors: [],
    discountPercent: "-25%",
    oldPrice: "98",
  },
  {
    id: 3,
    name: "Ramie shirt with pockets",
    price: 82.05,
    image: ["/ecom/women-20.jpg"],
    size: ["S", "M", "L", "XL"],
    colors: ["brown"],
    discountPercent: "-25%",
    oldPrice: "120",
  },
  {
    id: 4,
    name: "Ribbed cotton-blend top",
    price: 69.99,
    image: ["/ecom/women-30.jpg"],
    size: ["L", "XL"],
    colors: ["brown"],
    discountPercent: "",
    oldPrice: "",
  },
  {
    id: 5,
    name: "Ribbed cotton-blend top",
    price: 54.25,
    image: ["/ecom/women-84.jpg"],
    size: ["M", "L", "XL"],
    colors: ["white"],
    discountPercent: "",
    oldPrice: "",
  },
  {
    id: 6,
    name: "Faux-leather trousers",
    price: 29.1,
    image: ["/ecom/women-103.jpg"],
    size: ["S", "M", "L", "XL"],
    colors: ["black", "red"],
    discountPercent: "",
    oldPrice: "",
  },
  {
    id: 7,
    name: "Belt wrap dress",
    price: 98.16,
    image: ["/ecom/women-172.jpg"],
    size: ["S", "M", "L", "XL"],
    colors: ["white", "gray", "red"],
    discountPercent: "",
    oldPrice: "129.99",
  },
  {
    id: 8,
    name: "Double-button trench coat",
    price: 59.05,
    image: ["/ecom/women-179.jpg"],
    size: ["S", "M", "L", "XL"],
    colors: ["white", "gray", "red"],
    discountPercent: "",
    oldPrice: "69.05",
  },
];

export const Allproducts = [
  {
    id: 1,
    name: "V-neck cotton T-shirt",
    price: 59.99,
    image: [
      "/ecom/women-2.jpg",
      "/ecom/women-9.jpg",
      "/ecom/women-20.jpg",
      "/ecom/women-30.jpg",
      "/ecom/women-84.jpg",
    ],
    size: ["S", "M", "L", "XL"],
    colors: ["red", "blue", "green"],
    discountPercent: "",
    oldPrice: "",
  },
  {
    id: 2,
    name: "Polarized sunglasses",
    price: 79.54,
    image: [
      "/ecom/women-9.jpg",
      "/ecom/women-9.jpg",
      "/ecom/women-20.jpg",
      "/ecom/women-30.jpg",
      "/ecom/women-84.jpg",
    ],
    size: [],
    colors: [],
    discountPercent: "-25%",
    oldPrice: "98",
  },
  {
    id: 3,
    name: "Ramie shirt with pockets",
    price: 82.05,
    image: [
      "/ecom/women-20.jpg",
      "/ecom/women-9.jpg",
      "/ecom/women-20.jpg",
      "/ecom/women-30.jpg",
      "/ecom/women-84.jpg",
    ],
    size: ["S", "M", "L", "XL"],
    colors: ["brown"],
    discountPercent: "-25%",
    oldPrice: "120",
  },
  {
    id: 4,
    name: "Ribbed cotton-blend top",
    price: 69.99,
    image: [
      "/ecom/women-30.jpg",
      "/ecom/women-9.jpg",
      "/ecom/women-20.jpg",
      "/ecom/women-30.jpg",
      "/ecom/women-84.jpg",
    ],
    size: ["L", "XL"],
    colors: ["brown"],
    discountPercent: "",
    oldPrice: "",
  },
  {
    id: 5,
    name: "Ribbed cotton-blend top",
    price: 54.25,
    image: [
      "/ecom/women-84.jpg",
      "/ecom/women-9.jpg",
      "/ecom/women-20.jpg",
      "/ecom/women-30.jpg",
      "/ecom/women-84.jpg",
    ],
    size: ["M", "L", "XL"],
    colors: ["white"],
    discountPercent: "",
    oldPrice: "",
  },
  {
    id: 6,
    name: "Faux-leather trousers",
    price: 29.1,
    image: [
      "/ecom/women-103.jpg",
      "/ecom/women-9.jpg",
      "/ecom/women-20.jpg",
      "/ecom/women-30.jpg",
      "/ecom/women-84.jpg",
    ],
    size: ["S", "M", "L", "XL"],
    colors: ["black", "red"],
    discountPercent: "",
    oldPrice: "",
  },
  {
    id: 7,
    name: "Belt wrap dress",
    price: 98.16,
    image: [
      "/ecom/women-172.jpg",
      "/ecom/women-9.jpg",
      "/ecom/women-20.jpg",
      "/ecom/women-30.jpg",
      "/ecom/women-84.jpg",
    ],
    size: ["S", "M", "L", "XL"],
    colors: ["white", "gray", "red"],
    discountPercent: "",
    oldPrice: "129.99",
  },
  {
    id: 8,
    name: "Double-button trench coat",
    price: 59.05,
    image: [
      "/ecom/women-179.jpg",
      "/ecom/women-9.jpg",
      "/ecom/women-20.jpg",
      "/ecom/women-30.jpg",
      "/ecom/women-84.jpg",
    ],
    size: ["S", "M", "L", "XL"],
    colors: ["white", "gray", "red"],
    discountPercent: "",
    oldPrice: "69.05",
  },
  {
    id: 9,
    name: "Summer dress",
    price: 59.99,
    image: [
      "/ecom/men-3.jpg",
      "/ecom/women-9.jpg",
      "/ecom/women-20.jpg",
      "/ecom/women-30.jpg",
      "/ecom/women-84.jpg",
    ],
    size: ["S", "M", "L", "XL"],
    colors: ["red", "blue", "green"],
    discountPercent: "",
    oldPrice: "",
  },
  {
    id: 10,
    name: "Winter men",
    price: 59.99,
    image: [
      "/ecom/men-8.jpg",
      "/ecom/women-9.jpg",
      "/ecom/women-20.jpg",
      "/ecom/women-30.jpg",
      "/ecom/women-84.jpg",
    ],
    size: ["S", "M", "L", "XL"],
    colors: ["red", "blue", "green"],
    discountPercent: "",
    oldPrice: "",
  },
  {
    id: 11,
    name: "Summer men fit",
    price: 59.99,
    image: [
      "/ecom/men-11.jpg",
      "/ecom/women-9.jpg",
      "/ecom/women-20.jpg",
      "/ecom/women-30.jpg",
      "/ecom/women-84.jpg",
    ],
    size: ["S", "M", "L", "XL"],
    colors: ["red", "blue", "green"],
    discountPercent: "",
    oldPrice: "",
  },
  {
    id: 12,
    name: "Men winter",
    price: 59.99,
    image: [
      "/ecom/men-12.jpg",
      "/ecom/women-9.jpg",
      "/ecom/women-20.jpg",
      "/ecom/women-30.jpg",
      "/ecom/women-84.jpg",
    ],
    size: ["S", "M", "L", "XL"],
    colors: ["red", "blue", "green"],
    discountPercent: "",
    oldPrice: "",
  },
  {
    id: 13,
    name: "T-shirt men outfit",
    price: 59.99,
    image: [
      "/ecom/men-14.jpg",
      "/ecom/women-9.jpg",
      "/ecom/women-20.jpg",
      "/ecom/women-30.jpg",
      "/ecom/women-84.jpg",
    ],
    size: ["S", "M", "L", "XL"],
    colors: ["red", "blue", "green"],
    discountPercent: "",
    oldPrice: "",
  },
  {
    id: 14,
    name: "Men shirt dress",
    price: 59.99,
    image: [
      "/ecom/men-20.jpg",
      "/ecom/women-9.jpg",
      "/ecom/women-20.jpg",
      "/ecom/women-30.jpg",
      "/ecom/women-84.jpg",
    ],
    size: ["S", "M", "L", "XL"],
    colors: ["red", "blue", "green"],
    discountPercent: "",
    oldPrice: "",
  },
];
